### ISSUE TITLE
thermal ion version

### ISSUE THREAD

**Issue by wphu** [boutproject/SD1D#1]
I saw that you did some works using thermal ion version about scrape-off-layer, which is my interest. Can you give me the code, or upload it on the github, I will be very appreciated. I simulate 1D SOL using PIC code, and I want to do some comparision between PIC code and fluid code.

Thank you.

**Comment by bendudson** [comment]
Hi @wphu I don't know if this is still of interest, but if you need a hot ion (multi-fluid) version of SD1D then you might be interested in https://github.com/bendudson/hermes-3 which has 1D examples e.g. https://hermes3.readthedocs.io/en/latest/examples.html#d-flux-tube

**Comment by wphu** [comment]
@bendudson  Got it, thank you, I will move to hermes-3.
